version: '3.8'
services:
  flower_server:
    build: ./flower-server
    ports:
      - "8080:8080"
  
  # flower_client_1:
  #   build: ./flower-client
  #   volumes:
  #     - ./nodes/data_node_1:/client/data
  #   depends_on:
  #     - flower_server

  flower_client_2:
    build: ./flower-client
    volumes:
      - ./nodes/data_node_2:/client/data
    depends_on:
      - flower_server

  flower_client_3:
    build: ./flower-client
    volumes:
      - ./nodes/data_node_3:/client/data
    depends_on:
      - flower_server